[general]
import = ["~/.config/alacritty/themes/catppuccin-mocha.toml","~/.config/alacritty/keybindings.toml",]


[font]
size = 10.7

[font.bold]
family = "Cascadia Code"
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
family = "Cascadia Code"
style = "Italic"

[font.normal]
family = "Cascadia Code"
style = "Regular"

[window]
decorations = "none"

[window.padding]
x = 0
y = 0

