theme = "gruvbox_dark_hard"

[editor]
bufferline = "always"
cursorline = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
character = "╎"
skip-levels = 1

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
a = ["append_mode", "collapse_selection"] # Remove the selection when entering insert mode with 'a'
i = ["insert_mode", "collapse_selection"] # Remove the selection when entering insert mode with 'i'
"tab" = "goto_next_function" # Select and jump to the next function via Treesitter
"S-tab" = "goto_prev_function" # Select and jump to the previous function via Treesitter 
"home" = "goto_first_nonwhitespace" # Home jumps to first character in the line, not the beginning

# Mark line and move with them up/down
# https://github.com/helix-editor/helix/discussions/5764#discussioncomment-4840408
A-down = ["extend_to_line_bounds", "delete_selection", "paste_after"]
A-up = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]

# Duplicate lines up/down
# https://github.com/helix-editor/helix/issues/3680#issuecomment-1399443274
# Also in [keys.insert]
S-A-down = ["normal_mode", "extend_to_line_bounds", "yank", "open_below", "replace_with_yanked", "collapse_selection"]
S-A-up = ["normal_mode", "extend_to_line_bounds", "yank", "open_above", "replace_with_yanked", "collapse_selection"]

[keys.normal.space]
"." = "file_picker_in_current_buffer_directory"

[keys.insert]
# Duplicate lines up/down
# https://github.com/helix-editor/helix/issues/3680#issuecomment-1399443274
S-A-down = ["normal_mode", "extend_to_line_bounds", "yank", "open_below", "replace_with_yanked", "collapse_selection"]
S-A-up = ["normal_mode", "extend_to_line_bounds", "yank", "open_above", "replace_with_yanked", "collapse_selection"]
"home" = "goto_first_nonwhitespace" # Home jumps to first character in the line, not the beginning
