general {
    inhibit_sleep = 1
    lock_cmd = ~/bin/hypridle_session.sh lock
    # lock_cmd = pidof hyprlock || hyprlock       # avoid starting multiple hyprlock instances.
    on_lock_cmd = hyprctl hyprsunset gamma 100    # reset gamma if necessary
    on_unlock_cmd = /home/ricardo/bin/teams_fake_idle.sh off
    before_sleep_cmd = pidof hyprlock || hyprlock     # lock before suspend.
    after_sleep_cmd = hyprctl dispatch dpms on  # to avoid having to press a key twice to turn on the display.
}

listener {
    timeout = 580                                # 9:40 min
    on-timeout = hyprctl hyprsunset gamma 15     # set monitor backlight to minimum, 
    on-resume = hyprctl hyprsunset gamma 100     # monitor backlight restore.
}
listener {
    timeout = 600                                 # 10 min
    on-timeout = loginctl lock-session              # lock screen when timeout has passed
}

listener {
    timeout = 660                                  # 11 min
    on-timeout = hyprctl dispatch dpms off         # screen off when timeout has passed
    on-resume = hyprctl dispatch dpms on           # screen on when activity is detected after timeout has fired.
}
