-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-----------------
---- MONITORS ---
-----------------

local monitors = require("monitors")

local workspaces = require("workspaces")

--------------------
---- MY PROGRAMS ---
--------------------

local terminal = "alacritty"
local fileManager = "thunar"
local menu = "rofi -show drun"
local window_select = "rofi -show window"

------------------
---- AUTOSTART ---
------------------

hl.on("hyprland.start", function()
    hl.exec_cmd("settings set org.gnome.desktop.interface color-scheme \"prefer-dark\"")
    hl.exec_cmd("hyprpaper")
    hl.exec_cmd("waybar")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("hyprsunset")
    hl.exec_cmd("hyprctl dispatch workspace 2")
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("elephant")
    hl.exec_cmd("walker --gapplication-service")
end)

------------------------------
---- ENVIRONMENT VARIABLES ---
------------------------------

hl.env("XCURSOR_SIZE", 24)
hl.env("HYPRCURSOR_SIZE", 24)

----------------------
---- LOOK AND FEEL ---
----------------------

hl.config({
    general = {
        gaps_in = 3,
        gaps_out = 5,
        border_size = 2,
        -- Set to true enable resizing windows by clicking and dragging on borders and gaps
        resize_on_border = false,
        allow_tearing = false,
        layout = "dwindle",
        col = {
            active_border = "rgba(cba6f7aa)",
            inactive_border = "rgba(595959aa)",
        },
    },
    decoration = {
        rounding = 5,
        -- Change transparency of focused and unfocused windows
        active_opacity = 1.0,
        inactive_opacity = 0.95,
        shadow = {
            enabled = true,
            range = 4,
            render_power = 3,
            color = "rgba(1a1a1aee)",
        },
        blur = {
            enabled = true,
            size = 3,
            passes = 1,
            vibrancy = 0.1696,
        },
    },
    animations = {
        enabled = false,
    },
    dwindle = {
        preserve_split = true,
        -- You probably want this
        force_split = 2,
        -- new splits always to the right / bottom
    },
    master = {
        new_status = "master",
    },
    misc = {
        force_default_wallpaper = 0,
        -- Set to 0 or 1 to disable the anime mascot wallpapers
        disable_hyprland_logo = false,
        -- If true disables the random hyprland logo / anime girl background. :(
        disable_splash_rendering = true,
        key_press_enables_dpms = true,
    },
--------------
---- INPUT ---
--------------

    input = {
        kb_layout = "eu, de",
        kb_variant = ", nodeadkeys",
        -- kb_model = {  },###
        kb_options = "grp:shifts_toggle",
        -- kb_rules = {  },
        follow_mouse = 1,
        sensitivity = 0,
        -- -1.0 - 1.0, 0 means no modification.
        touchpad = {
            natural_scroll = false,
        },
    },
    debug = {
        disable_logs = true,
    },
})

--------------------
---- KEYBINDINGS ---
--------------------

-- Sets "Windows" key as main modifier
local mainMod = "SUPER"

hl.bind(mainMod .. " + " .. "return", hl.dsp.exec_cmd("alacritty"))
hl.bind(mainMod .. " + " .. "Q", hl.dsp.window.close())
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "E", hl.dsp.exit())
hl.bind(mainMod .. " + " .. "E", hl.dsp.exec_cmd("thunar"))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "space", hl.dsp.window.float())
hl.bind(mainMod .. " + " .. "D", hl.dsp.exec_cmd("rofi -show drun"))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "D", hl.dsp.exec_cmd("walker"))
hl.bind(mainMod .. " + " .. "P", hl.dsp.exec_cmd("rofi -show window"))
hl.bind(mainMod .. " + " .. "J", hl.dsp.layout("togglesplit"))

-- Move focus with mainMod + arrow keys

hl.bind(mainMod .. " + " .. "left", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + " .. "right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + " .. "up", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + " .. "down", hl.dsp.focus({ direction = "down" }))

-- Move window with mainMod + SHIFT + arrow keys

hl.bind(mainMod .. " + " .. " SHIFT " .. " + " .. "left", hl.dsp.window.move({ direction = "left" }))
hl.bind(mainMod .. " + " .. " SHIFT " .. " + " .. "right", hl.dsp.window.move({ direction = "right" }))
hl.bind(mainMod .. " + " .. " SHIFT " .. " + " .. "up", hl.dsp.window.move({ direction = "up" }))
hl.bind(mainMod .. " + " .. " SHIFT " .. " + " .. "down", hl.dsp.window.move({ direction = "down" }))

-- Switch workspaces with mainMod + [0-9]
hl.bind(mainMod .. " + " .. 1, hl.dsp.focus({ workspace = 1 }))
hl.bind(mainMod .. " + " .. 2, hl.dsp.focus({ workspace = 2 }))
hl.bind(mainMod .. " + " .. 3, hl.dsp.focus({ workspace = 3 }))
hl.bind(mainMod .. " + " .. 4, hl.dsp.focus({ workspace = 4 }))
hl.bind(mainMod .. " + " .. 5, hl.dsp.focus({ workspace = 5 }))
hl.bind(mainMod .. " + " .. 6, hl.dsp.focus({ workspace = 6 }))
hl.bind(mainMod .. " + " .. 7, hl.dsp.focus({ workspace = 7 }))
hl.bind(mainMod .. " + " .. 8, hl.dsp.focus({ workspace = 8 }))
hl.bind(mainMod .. " + " .. 9, hl.dsp.focus({ workspace = 9 }))
hl.bind(mainMod .. " + " .. 0, hl.dsp.focus({ workspace = 10 }))

-- Move active window to a workspace with mainMod + SHIFT + [0-9]
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 1, hl.dsp.window.move({ workspace = 1 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 2, hl.dsp.window.move({ workspace = 2 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 3, hl.dsp.window.move({ workspace = 3 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 4, hl.dsp.window.move({ workspace = 4 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 5, hl.dsp.window.move({ workspace = 5 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 6, hl.dsp.window.move({ workspace = 6 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 7, hl.dsp.window.move({ workspace = 7 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 8, hl.dsp.window.move({ workspace = 8 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 9, hl.dsp.window.move({ workspace = 9 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 0, hl.dsp.window.move({ workspace = 10 }))

-- Example special workspace (scratchpad)
hl.bind(mainMod .. " + " .. "S", hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "S", hl.dsp.window.move({ workspace = "special:magic" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(mainMod .. " + " .. "mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind(mainMod .. " + " .. "mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Laptop multimedia keys for volume and LCD brightness

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("pactl set-sink-volume @DEFAULT_SINK@ +5%"), { locked = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("pactl set-sink-volume @DEFAULT_SINK@ -5%"), { locked = true })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("pactl set-sink-mute @DEFAULT_SINK@ toggle"), { locked = true })
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), { locked = true })
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl s 10%+"), { locked = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl s 10%-"), { locked = true })

-- Requires playerctl
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })

-------------------------------
--## WINDOWS AND WORKSPACES ###
-------------------------------

-- Ignore maximize requests from apps. You'll probably like this.
local suppressMaximizeRule = hl.window_rule({
    -- Ignore maximize requests from all apps. You'll probably like this.
    name           = "suppress-maximize-events",
    match          = { class = ".*" },

    suppress_event = "maximize",
})
suppressMaximizeRule:set_enabled(true)

-- Fix some dragging issues with XWayland
-- windowrulev2 = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0


-- gsimplecal will be displayed on the top right corner, below the waybar date widget
hl.window_rule({
    name  = "gsimplecal_position",
    match = {
        class = "gsimplecal",
    },
    move  = "monitor_w-window_w-15 30",
})

-- wiremix: show as floating window
hl.window_rule({
    name  = "wiremix",
    match = {
        class = "wiremix-floating",
    },
    move  = { "monitor_w-window_w-100", 30 },
    pin   = true,
    float = true,
    size  = { 800, 600 },
})

------------------------
---- CUSTOM KEYBINDS ---
------------------------
hl.bind(mainMod .. " + " .. "f", hl.dsp.window.fullscreen())

-- Toggle group laylout
hl.bind(mainMod .. " + " .. "t", hl.dsp.group.toggle())

-- Move whole workspace to the left / right with SUPER + ALT + left/right
hl.bind(mainMod .. " + " .. " ALT " .. " + " .. " RIGHT ", hl.dsp.workspace.move({ monitor = "-1" }))
hl.bind(mainMod .. " + " .. " ALT " .. " + " .. " LEFT ", hl.dsp.workspace.move({ monitor = "+1" }))

-- Lock screen
hl.bind(mainMod .. " + " .. "L", hl.dsp.exec_cmd("loginctl lock-session"))

-- Screenshot with Print key

hl.bind("PRINT", hl.dsp.exec_cmd("flameshot screen --number $(hyprctl activeworkspace -j| jq '.monitorID') --edit"))
hl.bind("SHIFT" .. " + " .. "PRINT", hl.dsp.exec_cmd("local_var_HOME/bin/record_region.sh"))

-- Submap for Program shortcuts (Ctrl+k  + <binding>)

hl.bind(mainMod .. " + " .. "K", hl.dsp.submap("launch"))

hl.define_submap("launch", function()
    hl.bind("t", hl.dsp.exec_cmd("$HOME/Apps/teams-for-linux-2.7.13.AppImage"))
    hl.bind("t", hl.dsp.submap("reset"))
    hl.bind("b", hl.dsp.exec_cmd("firefox"))
    hl.bind("b", hl.dsp.submap("reset"))
    hl.bind("v", hl.dsp.exec_cmd("$HOME/.scripts/vnc/dmenu-vnc-rdp.sh"))
    hl.bind("v", hl.dsp.submap("reset"))
    hl.bind("N", hl.dsp.exec_cmd("alacritty -e nvim local_var_HOME/notes"))
    hl.bind("n", hl.dsp.submap("reset"))
    hl.bind("ESCAPE", hl.dsp.submap("reset"))
end)

-- hyprwhspr - Toggle mode (added by hyprwhspr setup)
-- Press once to start, press again to stop
hl.bind("SUPER + ALT" .. " + " .. "D", hl.dsp.exec_cmd("/usr/lib/hyprwhspr/config/hyprland/hyprwhspr-tray.sh record"))

