-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Generated by nwg-displays on 2026-02-26 at 14:02:16. Do not edit manually.

hl.monitor({
    -- output   = "HDMI-A-1",
    output   = "desc:Iiyama North America PL2480H 11182M3300120",
    mode     = "1920x1080@60.0",
    position = "0x131",
    scale    = 1.0,
})

hl.monitor({
    -- output   = "DP-2",
    output   = "desc:LG Electronics LG TV 0x01010101",
    mode     = "1920x1080@60.0",
    position = "2240x-1080",
    scale    = 1.0,
})

hl.monitor({
    -- output   = "DP-4",
    output   = "desc:Dell Inc. DELL U2715H GH85D76G1K2S",
    mode     = "2560x1440@59.95",
    position = "1920x0",
    scale    = 1.0,
})

