-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Generated by nwg-displays on 2026-02-26 at 14:02:16. Do not edit manually.

hl.monitor({
    output   = "HDMI-A-1",
    mode     = "1920x1080@60.0",
    position = "0x131",
    scale    = 1.0,
})

hl.monitor({
    output   = "HDMI-A-3",
    mode     = "1920x1080@60.0",
    position = "4480x131",
    scale    = 1.0,
})

hl.monitor({
    output   = "DP-4",
    mode     = "2560x1440@59.95",
    position = "1920x0",
    scale    = 1.0,
})
