-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Generated by nwg-displays on 2026-02-26 at 14:02:14. Do not edit manually.

hl.workspace_rule({
    workspace = 1,
    monitor = "HDMI-A-1",
    -- is_default = false,
})

hl.workspace_rule({
    workspace = 2,
    monitor = "DP-4",
    -- is_default = true,
})

hl.workspace_rule({
    workspace = 3,
    monitor = "HDMI-A-3",
    -- is_default = true,
})
